on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Actions of GitHub'
        run: pwd

      - name: ' Printing  Name'
        run: echo 'Hana Shaker'

      - name: 'Printing File Content Before '
        run: ls

      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Printing File Content After '
        run: ls 

      - name: "Login to Docker Hub"
        run: docker login --username ${{ secrets.DOCKERUSERNAME }} --password ${{ secrets.DOCKERTOKEN }}   